# PakWheels Used Cars â€” Week 4
**Objective:** Clean and perform EDA; prepare dataset for regression tasks.

In [20]:
# Example path (adjust to where you put the CSVs in Drive)
weather_path = '/content/drive/MyDrive/dataset assignment_dataset/weather_classification_data.csv'
reg_path = '/content/drive/MyDrive/dataset assignment_dataset/pakwheels_used_cars.csv'

In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

In [22]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [23]:
reg_csv = REG_DIR / "pakwheels_used_cars.csv"
df_reg = pd.read_csv('/content/drive/MyDrive/dataset/assignment_dataset/pakwheels_used_cars.csv')
display(df_reg.head())
display(df_reg.info())
display(df_reg.describe(include='all').T)
print("Missing values:\n", df_reg.isnull().sum())

,ad_ref,assembly,body,ad_city,color,engine_cc,fuel_type,make,mileage,model,registered,transmission,year,price
0,7927285,Imported,Van,Lahore,Pearl White,2000.0,Hybrid,Nissan,124000,Serena,Un-Registered,Automatic,1905.0,8990000.0
1,7679303,Imported,Hatchback,Lahore,Grey,996.0,Petrol,Toyota,30738,Vitz,Punjab,Automatic,1905.0,4190000.0
2,7915479,NaN,Sedan,Lahore,Super white,1798.0,Petrol,Toyota,183000,Corolla,Punjab,Automatic,1905.0,3990000.0
3,7918380,NaN,Sedan,Lahore,Crystal Black Pearl,1500.0,Petrol,Honda,41000,Civic,Punjab,Automatic,1905.0,6490000.0
4,7676167,Imported,MPV,Lahore,Silver,3000.0,Petrol,Toyota,126000,Alphard,Punjab,Automatic,1905.0,4750000.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77237 entries, 0 to 77236
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ad_ref        77237 non-null  int64
 1   assembly      23976 non-null  object
 2   body          68372 non-null  object
 3   ad_city       77237 non-null  object
 4   color         75727 non-null  object
 5   engine_cc     77235 non-null  float64
 6   fuel_type     76303 non-null  object
 7   make          77237 non-null  object
 8   mileage       77237 non-null  int64
 9   model         77237 non-null  object
 10  registered    77237 non-null  object
 11  transmission  77237 non-null  object
 12  year          72516 non-null  float64
 13  price         76588 non-null  float64
dtypes: float64(3), int64(2), object(9)
memory usage: 8.2+ MB

None

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
ad_ref,77237.0,NaN,NaN,NaN,7797474.225643,256967.873332,274897.0,7792632.0,7853515.0,7897048.0,7931906.0
assembly,23976,1,Imported,23976,NaN,NaN,NaN,NaN,NaN,NaN,NaN
body,68372,21,Sedan,29951,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ad_city,77237,297,Lahore,16418,NaN,NaN,NaN,NaN,NaN,NaN,NaN
color,75727,386,White,21324,NaN,NaN,NaN,NaN,NaN,NaN,NaN
engine_cc,77235.0,NaN,NaN,NaN,1406.452062,707.665165,3.0,1000.0,1300.0,1600.0,15000.0
fuel_type,76303,3,Petrol,70028,NaN,NaN,NaN,NaN,NaN,NaN,NaN
make,77237,69,Toyota,24678,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mileage,77237.0,NaN,NaN,NaN,91296.829589,89705.138633,1.0,34000.0,80000.0,123456.0,1000000.0
model,77237,432,Corolla,12762,NaN,NaN,NaN,NaN,NaN,NaN,NaN
registered,77237,128,Lahore,18677,NaN,NaN,NaN,NaN,NaN,NaN,NaN
transmission,77237,2,Automatic,42010,NaN,NaN,NaN,NaN,NaN,NaN,NaN
year,72516.0,NaN,NaN,NaN,1905.0,0.0,1905.0,1905.0,1905.0,1905.0,1905.0
price,76588.0,NaN,NaN,NaN,3854192.57586,5576969.960317,120000.0,1425000.0,2650000.0,4500000.0,180000000.0

Missing values:
 ad_ref              0
assembly        53261
body             8865
ad_city             0
color            1510
engine_cc           2
fuel_type         934
make                0
mileage             0
model               0
registered          0
transmission        0
year             4721
price             649
dtype: int64

In [ ]:
# Quick Cleaning Plan (implementation)
# Convert price and mileage to numeric (strip non-digit chars).
# Explore price distribution and use log(price) for skewed visualization.
# For make and model (high cardinality): keep top N categories and replace the rest with 'Other'.
# Handle missing values and outliers; save cleaned CSV in regression/.

In [24]:
display(df_reg.shape)
display(df_reg.info())
display(df_reg.head())
print("Missing values:\n", df_reg.isnull().sum())

(77237, 14)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77237 entries, 0 to 77236
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ad_ref        77237 non-null  int64
 1   assembly      23976 non-null  object
 2   body          68372 non-null  object
 3   ad_city       77237 non-null  object
 4   color         75727 non-null  object
 5   engine_cc     77235 non-null  float64
 6   fuel_type     76303 non-null  object
 7   make          77237 non-null  object
 8   mileage       77237 non-null  int64
 9   model         77237 non-null  object
 10  registered    77237 non-null  object
 11  transmission  77237 non-null  object
 12  year          72516 non-null  float64
 13  price         76588 non-null  float64
dtypes: float64(3), int64(2), object(9)
memory usage: 8.2+ MB

None

,ad_ref,assembly,body,ad_city,color,engine_cc,fuel_type,make,mileage,model,registered,transmission,year,price
0,7927285,Imported,Van,Lahore,Pearl White,2000.0,Hybrid,Nissan,124000,Serena,Un-Registered,Automatic,1905.0,8990000.0
1,7679303,Imported,Hatchback,Lahore,Grey,996.0,Petrol,Toyota,30738,Vitz,Punjab,Automatic,1905.0,4190000.0
2,7915479,NaN,Sedan,Lahore,Super white,1798.0,Petrol,Toyota,183000,Corolla,Punjab,Automatic,1905.0,3990000.0
3,7918380,NaN,Sedan,Lahore,Crystal Black Pearl,1500.0,Petrol,Honda,41000,Civic,Punjab,Automatic,1905.0,6490000.0
4,7676167,Imported,MPV,Lahore,Silver,3000.0,Petrol,Toyota,126000,Alphard,Punjab,Automatic,1905.0,4750000.0

Missing values:
 ad_ref              0
assembly        53261
body             8865
ad_city             0
color            1510
engine_cc           2
fuel_type         934
make                0
mileage             0
model               0
registered          0
transmission        0
year             4721
price             649
dtype: int64

In [25]:
# Clean price and mileage columns (adjust names if slightly different)
def to_numeric_strip(s):
    return pd.to_numeric(s.astype(str).str.replace(r'[^0-9.]', '', regex=True).replace('', np.nan), errors='coerce')

if 'price' in df_reg.columns:
    df_reg['price'] = to_numeric_strip(df_reg['price'])
if 'mileage' in df_reg.columns:
    df_reg['mileage'] = to_numeric_strip(df_reg['mileage'])
if 'engine_cc' in df_reg.columns:
    df_reg['engine_cc'] = to_numeric_strip(df_reg['engine_cc'])
# convert year to numeric if necessary
if 'year' in df_reg.columns:
    df_reg['year'] = pd.to_numeric(df_reg['year'], errors='coerce')

# report
print("After conversion â€” price NaNs:", df_reg['price'].isna().sum() if 'price' in df_reg.columns else 'no price col')
print("mileage NaNs:", df_reg['mileage'].isna().sum() if 'mileage' in df_reg.columns else 'no mileage col')
display(df_reg[['price','mileage','engine_cc','year']].describe().T)

After conversion â€” price NaNs: 649
mileage NaNs: 0

,count,mean,std,min,25%,50%,75%,max
price,76588.0,3.854193e+06,5.576970e+06,120000.0,1425000.0,2650000.0,4500000.0,180000000.0
mileage,77237.0,9.129683e+04,8.970514e+04,1.0,34000.0,80000.0,123456.0,1000000.0
engine_cc,77235.0,1.406452e+03,7.076652e+02,3.0,1000.0,1300.0,1600.0,15000.0
year,72516.0,1.905000e+03,0.000000e+00,1905.0,1905.0,1905.0,1905.0,1905.0

In [26]:
# Strategy: drop rows with missing target price; for other numeric cols impute with median; categorical impute with 'Unknown'
if 'price' in df_reg.columns:
    before = df_reg.shape[0]
    df_reg = df_reg.dropna(subset=['price']).reset_index(drop=True)
    print(f"Dropped {before - df_reg.shape[0]} rows with missing price")

# Fill numeric NaNs with median
num_cols_reg = df_reg.select_dtypes(include=['number']).columns.tolist()
num_cols_reg.remove('price') if 'price' in num_cols_reg else None
for c in num_cols_reg:
    median = df_reg[c].median()
    df_reg[c] = df_reg[c].fillna(median)

# Fill categorical NaNs
cat_cols_reg = df_reg.select_dtypes(include=['object','category']).columns.tolist()
for c in cat_cols_reg:
    df_reg[c] = df_reg[c].fillna('Unknown')

print("Missing values after imputation:\n", df_reg.isnull().sum().sort_values(ascending=False).head(20))

Dropped 649 rows with missing price
Missing values after imputation:
 ad_ref          0
assembly        0
body            0
ad_city         0
color           0
engine_cc       0
fuel_type       0
make            0
mileage         0
model           0
registered      0
transmission    0
year            0
price           0
dtype: int64

In [27]:
# choose top N
top_makes = 15
top_models = 25

if 'make' in df_reg.columns:
    top_make_vals = df_reg['make'].value_counts().nlargest(top_makes).index
    df_reg['make_reduced'] = df_reg['make'].where(df_reg['make'].isin(top_make_vals), other='Other')
if 'model' in df_reg.columns:
    top_model_vals = df_reg['model'].value_counts().nlargest(top_models).index
    df_reg['model_reduced'] = df_reg['model'].where(df_reg['model'].isin(top_model_vals), other='Other')
if 'city' in df_reg.columns:
    top_city_vals = df_reg['city'].value_counts().nlargest(20).index
    df_reg['city_reduced'] = df_reg['city'].where(df_reg['city'].isin(top_city_vals), other='Other')

# quick check
for newcol in ['make_reduced','model_reduced','city_reduced']:
    if newcol in df_reg.columns:
        print(newcol, df_reg[newcol].nunique())

make_reduced 16
model_reduced 26

In [28]:
plt.figure(figsize=(6,4))
plt.hist(df_reg['price'].dropna(), bins=50)
plt.title('Price distribution (raw)')
plt.xlabel('Price'); plt.ylabel('Count')
plt.tight_layout()
plt.savefig(REG_DIR / "price_hist_raw.png")
plt.close()

# log price
import numpy as np
df_reg['log_price'] = np.log1p(df_reg['price'])
plt.figure(figsize=(6,4))
plt.hist(df_reg['log_price'].dropna(), bins=50)
plt.title('Price distribution (log1p)')
plt.xlabel('log1p(price)'); plt.ylabel('Count')
plt.tight_layout()
plt.savefig(REG_DIR / "price_hist_log.png")
plt.close()
print("Saved price histograms to regression/figures")

Saved price histograms to regression/figures

In [29]:
# Boxplot: price by top makes (use log price to reduce skew)
if 'make_reduced' in df_reg.columns:
    plt.figure(figsize=(10,5))
    order = df_reg.groupby('make_reduced')['price'].median().sort_values(ascending=False).index
    sns.boxplot(x='make_reduced', y='log_price', data=df_reg, order=order)
    plt.xticks(rotation=45)
    plt.title('Log-price by make (reduced)')
    plt.tight_layout()
    plt.savefig(REG_DIR / "box_price_by_make.png")
    plt.close()

# Scatter: price vs mileage
if 'mileage' in df_reg.columns:
    plt.figure(figsize=(6,4))
    plt.scatter(df_reg['mileage'], df_reg['price'], alpha=0.4, s=8)
    plt.xlabel('Mileage (km)'); plt.ylabel('Price (PKR)')
    plt.title('Price vs Mileage')
    plt.tight_layout()
    plt.savefig(REG_DIR / "price_vs_mileage.png")
    plt.close()

print("Saved regression EDA plots to regression/figures")

Saved regression EDA plots to regression/figures

In [30]:
num_reg = ['price','log_price','mileage','engine_cc','year']
present = [c for c in num_reg if c in df_reg.columns]
if len(present) > 1:
    plt.figure(figsize=(8,6))
    sns.heatmap(df_reg[present].corr(), annot=True, fmt=".2f", cmap='coolwarm')
    plt.title('Correlation among numeric regression features')
    plt.tight_layout()
    plt.savefig(REG_DIR / "regression_correlation_heatmap.png")
    plt.close()
    print("Saved correlation heatmap")
else:
    print("Not enough numeric regression columns for correlation heatmap.")

Saved correlation heatmap

## Regression EDA findings & conclusion

- Summarize the key insights: e.g., price skewness, top makes with higher median price, correlation of price with year/mileage/engine_cc.
- Mention any data issues and how you handled them.
- Save cleaned dataset to regression/pakwheels_used_cars_cleaned.csv for future modeling.

In [31]:
clean_reg_path = REG_DIR / "pakwheels_used_cars_cleaned.csv"
df_reg.to_csv(clean_reg_path, index=False)
print("Saved cleaned regression dataset to:", clean_reg_path)

Saved cleaned regression dataset to: Buildable-ML-DL-Fellowship\week4/regression/pakwheels_used_cars_cleaned.csv

In [32]:
# Train simple regression models for evaluation (if you want to include regression models)
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np


if 'df_reg' not in globals():
    print("df_reg not found. Please make sure the regression dataframe is loaded.")
else:
    X_cols = []
    # prefer reduced columns if exist
    for c in ['make_reduced','model_reduced','city_reduced']:
        if c in df_reg.columns:
            X_cols.append(c)
    for c in ['mileage','engine_cc','year']:
        if c in df_reg.columns:
            X_cols.append(c)
    if len(X_cols) == 0:
        X_cols = df_reg.select_dtypes(include=['number']).columns.tolist()
        X_cols = [c for c in X_cols if c!='price']

    # Drop rows with NaNs in selected features (should be rare after imputation)
    df_reg_model = df_reg.dropna(subset=X_cols + (['price'] if 'price' in df_reg.columns else []))
    X = df_reg_model[X_cols]
    y = df_reg_model['price']

    from sklearn.impute import SimpleImputer
    from sklearn.preprocessing import StandardScaler, OneHotEncoder
    from sklearn.compose import ColumnTransformer
    from sklearn.pipeline import Pipeline
    num_feats = X.select_dtypes(include=['number']).columns.tolist()
    cat_feats = X.select_dtypes(include=['object','category']).columns.tolist()

    num_pipe = Pipeline([('imputer', SimpleImputer(strategy='median')), ('scaler', StandardScaler())])
    cat_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('ohe', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
])
    preproc_reg = ColumnTransformer([('num', num_pipe, num_feats), ('cat', cat_pipe, cat_feats)])

    from sklearn.model_selection import train_test_split
    Xtr, Xte, ytr, yte = train_test_split(X, y, test_size=0.2, random_state=42)


    lr_pipe = Pipeline([('preproc', preproc_reg), ('model', LinearRegression())])
    lr_pipe.fit(Xtr, ytr)
    ypred_lr = lr_pipe.predict(Xte)
    lr_metrics = {
        'model': 'LinearRegression',
        'rmse': np.sqrt(mean_squared_error(yte, ypred_lr)),
        'mae': mean_absolute_error(yte, ypred_lr),
        'r2': r2_score(yte, ypred_lr)
    }
    print("Linear Regression metrics:", lr_metrics)

    rfr_pipe = Pipeline([('preproc', preproc_reg), ('model', RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1))])
    rfr_pipe.fit(Xtr, ytr)
    ypred_rfr = rfr_pipe.predict(Xte)
    rfr_metrics = {
        'model': 'RandomForestRegressor',
        'rmse': np.sqrt(mean_squared_error(yte, ypred_rfr)),
        'mae': mean_absolute_error(yte, ypred_rfr),
        'r2': r2_score(yte, ypred_rfr)
    }
    print("RandomForestRegressor metrics:", rfr_metrics)

    # Save metrics table
    import pandas as pd
    metrics_df = pd.DataFrame([lr_metrics, rfr_metrics]).set_index('model')
    display(metrics_df)
    metrics_df.to_csv(REG_DIR / "regression_model_metrics.csv")
    print("Saved regression metrics to", REG_DIR / "regression_model_metrics.csv")

Linear Regression metrics: {'model': 'LinearRegression', 'rmse': np.float64(4289961.211933644), 'mae': 1668050.0970646304, 'r2': 0.3675515134903159}
RandomForestRegressor metrics: {'model': 'RandomForestRegressor', 'rmse': np.float64(2664858.0617347728), 'mae': 888745.2722260273, 'r2': 0.7559568674607128}

                               rmse           mae        r2
model
LinearRegression       4.289961e+06  1.668050e+06  0.367552
RandomForestRegressor  2.664858e+06  8.887453e+05  0.755957

Saved regression metrics to Buildable-ML-DL-Fellowship\week4/regression/regression_model_metrics.csv

In [33]:
BASE = Path(r"Buildable-ML-DL-Fellowship\week4")
REG_DIR = BASE / "regression"
FIG_DIR = REG_DIR / "figures"
FIG_DIR.mkdir(parents=True, exist_ok=True)

In [34]:
import matplotlib.pyplot as plt
import numpy as np
if 'ypred_rfr' in globals():
    plt.figure(figsize=(6,6))
    plt.scatter(yte, ypred_rfr, alpha=0.3, s=6)
    plt.plot([yte.min(), yte.max()], [yte.min(), yte.max()], 'r--')
    plt.xlabel('Actual Price'); plt.ylabel('Predicted Price'); plt.title('Actual vs Predicted (RandomForest)')
    plt.tight_layout()
    plt.savefig(REG_DIR / "actual_vs_predicted_rfr.png")
    plt.close()

    # residuals
    residuals = yte - ypred_rfr
    plt.figure(figsize=(6,4))
    plt.scatter(ypred_rfr, residuals, alpha=0.3, s=6)
    plt.hlines(0, xmin=ypred_rfr.min(), xmax=ypred_rfr.max(), colors='r', linestyles='dashed')
    plt.xlabel('Predicted Price'); plt.ylabel('Residual (Actual - Predicted)'); plt.title('Residuals vs Predicted (RandomForest)')
    plt.tight_layout()
    plt.savefig(REG_DIR / "residuals_vs_predicted_rfr.png")
    plt.close()
    print("Saved actual vs predicted and residual plots to", REG_DIR)
else:
    print("No predictions found (ypred_rfr). Did you run the regression training cell?")

Saved actual vs predicted and residual plots to Buildable-ML-DL-Fellowship\week4/regression

In [35]:
if 'df_reg' in globals():
    clean_reg_path = REG_DIR / "pakwheels_used_cars_cleaned.csv"
    df_reg.to_csv(clean_reg_path, index=False)
    print("Saved cleaned regression dataset to:", clean_reg_path)
else:
    print("df_reg not found, cannot save cleaned CSV.")

Saved cleaned regression dataset to: Buildable-ML-DL-Fellowship\week4/regression/pakwheels_used_cars_cleaned.csv